Kadai3
RyuyaMaeda/Java-Study pull request #10
Opened 2020-04-27 23:50 UTC by RyuyaMaeda

@kimidoriam @shunji-yamaguchi 
３章の練習問題の提出です。
レビューの方、よろしくお願いします。

2020-04-28 00:22 UTC, shunji-yamaguchi requested changes
@RyuyaMaeda 
レビューしました。ご確認をよろしくお願いします。

2020-04-28 00:22 UTC, shunji-yamaguchi commented on src/kadai1/kadai1_2.java
> +public class kadai1_2 {
@RyuyaMaeda 
第１章の課題がコミットされてます。
このブランチは第３章の課題をするものなので、関係ないファイルはコミットすべきではないです。
削除しておいてください。

2020-04-28 02:22 UTC, RyuyaMaeda commented on src/kadai1/kadai1_2.java
> +public class kadai1_2 {
@shunji-yamaguchi 
一章の課題のコミットを削除しておきました。
レビューの方よろしくお願いします。

2020-04-28 09:02 UTC, kimidoriam approved these changes
良いと思います :ok_woman:

2020-04-30 00:01 UTC, shunji-yamaguchi commented
@RyuyaMaeda 良いと思います 🆗

2020-04-30 00:02 UTC, shunji-yamaguchi approved these changes

2020-04-30 00:10 UTC, merged