Kadai5
RyuyaMaeda/Java-Study pull request #12
Opened 2020-04-30 07:02 UTC by RyuyaMaeda

5章の練習問題です。レビューよろしくお願いします。

2020-04-30 07:58 UTC, kimidoriam requested changes
レビューしました。ご確認をお願いします。

2020-04-30 07:58 UTC, kimidoriam commented on src/kadai5/Kadai5_2.java
> +    }
メソッドが複数ある場合は改行を入れると良いです。

2020-04-30 07:58 UTC, kimidoriam commented on src/kadai5/Kadai5_1.java
> +    }
メソッドが複数ある場合は改行を入れると良いです。

2020-04-30 07:58 UTC, kimidoriam commented on src/kadai5/Kadai5_3.java
> +    }
メソッドが複数ある場合は改行を入れると良いです。

2020-04-30 07:58 UTC, kimidoriam commented on src/kadai5/Kadai5_3.java
> +    }
メソッドが複数ある場合は改行を入れると良いです。

2020-04-30 07:58 UTC, kimidoriam commented on src/kadai5/Kadai5_3.java
> +        System.out.println(address + "に、" + "以下のメールを送信しました");
文字列の結合は1回で良いのではないでしょうか。

2020-04-30 07:58 UTC, kimidoriam commented on src/kadai5/Kadai5_3.java
> +        System.out.println(address + "に、" + "以下のメールを送信しました");
文字列の結合は1回で良いのではないでしょうか。

2020-04-30 07:58 UTC, kimidoriam commented on src/kadai5/Kadai5_4.java
> +    }
メソッドが複数ある場合は改行を入れると良いです。

2020-04-30 07:58 UTC, kimidoriam commented on src/kadai5/Kadai5_4.java
> +    }
メソッドが複数ある場合は改行を入れると良いです。

2020-04-30 07:58 UTC, kimidoriam commented on src/kadai5/Kadai5_2.java
> +        System.out.println(address + "に、" + "以下のメールを送信しました");
文字列の結合は1回で良いのではないでしょうか。

2020-04-30 08:18 UTC, RyuyaMaeda commented
@kimidoriam 
レビューありがとうございます。
各メソッドの間に改行を挿入、文字列結合の修正をしました。
よろしくお願いします。

2020-04-30 08:33 UTC, kimidoriam approved these changes
良いと思います :ok_woman:

2020-05-01 08:47 UTC, shunji-yamaguchi approved these changes
@RyuyaMaeda 良いと思います 🆗

2020-05-07 01:25 UTC, merged