Kadai6
RyuyaMaeda/Java-Study pull request #13
Opened 2020-05-01 05:19 UTC by RyuyaMaeda

6章の練習問題です。
レビューよろしくお願いします。

2020-05-01 08:59 UTC, shunji-yamaguchi requested changes
@RyuyaMaeda レビューしました、ご確認をよろしくお願いします。

2020-05-01 08:59 UTC, shunji-yamaguchi commented on src/kadai6/kadai6_1/Main.java
> +}
ファイルの最後に改行がないため、GitHub上で警告が表示されます。
改行を追加しておきましょう。

2020-05-07 01:22 UTC, RyuyaMaeda commented on src/kadai6/kadai6_1/Main.java
> +}
@shunji-yamaguchi 
レビューありがとうございます。
最後に改行を挿入しました。
よろしくお願いします！

2020-05-07 08:15 UTC, shunji-yamaguchi approved these changes
@RyuyaMaeda 良いと思います 🆗

2020-05-08 05:27 UTC, kimidoriam approved these changes
良いと思います :ok_woman:

2020-05-08 05:41 UTC, merged