Kadai8
RyuyaMaeda/Java-Study pull request #14
Opened 2020-05-07 07:24 UTC by RyuyaMaeda

@kimidoriam @shunji-yamaguchi
８章の練習問題です。
レビューの方よろしくお願いします。

2020-05-07 09:12 UTC, shunji-yamaguchi requested changes
@RyuyaMaeda レビューしました、ご確認をよろしくお願いします。

2020-05-07 09:12 UTC, shunji-yamaguchi commented on src/kadai8/kadai8_2/Cleric.java
> + * 練習８−１で宣言したクラスClericに「名前」「HP」「最大HP」「MP」「最大MP」を属性として追加
このファイルは`練習問題8-2`の回答です、コメントに誤りがあるので修正しておいてください。

2020-05-07 09:12 UTC, shunji-yamaguchi commented on src/kadai8/kadai8_3/Cleric.java
> + * 練習８−２で宣言したクラスClericにMPを５消費してHPを最大まで回復するメソッドselfAid()を追加
これも`練習8-3`に修正しておいてください。

2020-05-07 09:12 UTC, shunji-yamaguchi commented on src/kadai8/kadai8_4/Cleric.java
> + * 練習８−３で宣言したクラスClericにMPを回復するメソッドpray()を追加
これも`練習8-4`に修正しておいてください。

2020-05-07 09:12 UTC, shunji-yamaguchi commented on src/kadai8/kadai8_4/Cleric.java
> +    }
mpが5未満のときもセルフエイドを唱えられるのが気になりました。
せっかくなのでmpが足りないと失敗するように修正してみてください 🙏

2020-05-07 09:12 UTC, shunji-yamaguchi commented on Java-Study.iml
> +<?xml version="1.0" encoding="UTF-8"?>
outディレクトリ配下のビルドしたclassファイルがコミットされています。
これらはソースコードではないのでコミットすべきではないです。
`.gitignore`ファイルでoutディレクトリ配下をGit管理の対象外としておくと良いです。

`.iml`ファイルにはこのプロジェクトの設定内容が保存されているようです。
gitで管理するのかはプロジェクトによるみたいなので、コミットするかはおまかせします。

2020-05-08 04:49 UTC, RyuyaMaeda commented
@shunji-yamaguchi 
レビューありがとうございます。以下の点を修正いたしました。
- コメントの編集
- classファイルのコミットの削除
- selfAid()の修正
よろしくお願いします。

2020-05-08 05:48 UTC, kimidoriam commented on src/kadai8/kadai8_2/Cleric.java
> + * 練習８−１で宣言したクラスClericに「名前」「HP」「最大HP」「MP」「最大MP」を属性として追加
練習問題8-2の内容が、「8-1で作ったクラスに属性を追加せよ」なので、元のコメントで合ってるんじゃないでしょうか？（以下同様です）

2020-05-08 05:56 UTC, kimidoriam requested changes
レビューしました。ご確認をお願いします。

それとGitで迷子になっているようにお見受けしますが、大丈夫ですか？
不必要なコミットはなかったことにできるので、試してみても良いかもしれません。
（`git reset`や`git rebase`などで調べてみてください）

2020-05-08 05:56 UTC, kimidoriam commented on src/kadai8/kadai8_3/Cleric.java
> +        if(this.mp >= 5) {
`if`のあとにスペースを入れると見やすくなります。

2020-05-08 09:22 UTC, shunji-yamaguchi commented on src/kadai8/kadai8_2/Cleric.java
> + * 練習８−１で宣言したクラスClericに「名前」「HP」「最大HP」「MP」「最大MP」を属性として追加
あ、ほんとですね。失礼しました 🙇

2020-05-08 09:22 UTC, shunji-yamaguchi approved these changes
@RyuyaMaeda 追加の指摘ありません。良いと思います 🆗

2020-05-11 05:46 UTC, RyuyaMaeda commented on src/kadai8/kadai8_3/Cleric.java
> +        if(this.mp >= 5) {
@kimidoriam 
レビューありがとうございます。
ifの後にスペースを追加しました。
よろしくお願いします。

2020-05-13 07:51 UTC, kimidoriam approved these changes
確認しました。良いと思います :ok_woman:

2020-05-14 00:12 UTC, merged