Kadai11
RyuyaMaeda/Java-Study pull request #18
Opened 2020-05-13 02:52 UTC by RyuyaMaeda

@shunji-yamaguchi @kimidoriam 
11章の練習問題です。
レビューの方よろしくお願いします。

2020-05-14 09:20 UTC, shunji-yamaguchi approved these changes
@RyuyaMaeda 良いと思います 🆗

2020-05-14 09:25 UTC, kimidoriam requested changes
レビューしました。ご確認をお願いします。

2020-05-14 09:25 UTC, kimidoriam commented on src/kadai11/kadai11_1/Book.java
> +public class Book extends TangibleAsset{
`{`の前にスペースを入れましょう。

2020-05-14 09:25 UTC, kimidoriam commented on src/kadai11/kadai11_1/Computer.java
> +public class Computer extends TangibleAsset{
`{`の前にスペースを入れましょう。

2020-05-15 05:38 UTC, RyuyaMaeda commented
@kimidoriam 
レビューありがとうございます。
Book.javaとComputer.javaの３行目の { の前にスペースを挿入しました。
よろしくお願いします。

2020-05-26 09:22 UTC, kimidoriam approved these changes
確認しました。良いと思います :ok_woman:

2020-05-27 00:05 UTC, merged