Kadai13
RyuyaMaeda/Java-Study pull request #20
Opened 2020-05-18 07:22 UTC by RyuyaMaeda

@shunji-yamaguchi @kimidoriam 
１３章の練習問題です。
練習問題13-1の回答プログラムのままだとコンパイルエラーが発生するので、練習問題13-1と13-3をまとめてみました。
レビューの方よろしくお願いします。

2020-05-19 09:50 UTC, shunji-yamaguchi requested changes
@RyuyaMaeda レビューしました。ご確認よろしくお願いします。

2020-05-19 09:50 UTC, shunji-yamaguchi commented on src/kadai13/kadai13_3/Main.java
> +        h.setHp(100);
（教本のサンプルコードがそうなっているのですが）
Heroクラスのインスタンスの変数名を`h`とするのは良くないです。
変数名を見てもそれがなんなのか分からないので。
`wand`や`wizard`と同じように、`hero`とするのが良いです。

2020-05-19 09:50 UTC, shunji-yamaguchi commented on src/kadai13/kadai13_4/Wizard.java
> +            throw new IllegalArgumentException("mpを設定できません。処理を中断。");
`処理を中断。`という表現は不要かなと思います。
例外が投げられたことより正常に処理していないことは分かるので。

2020-05-19 09:50 UTC, shunji-yamaguchi commented on src/kadai13/kadai13_4/Wizard.java
> +            throw new IllegalArgumentException("杖を装備してください。処理を中断。");
`処理を中断。`という表現は不要かなと思います。
例外が投げられたことより正常に処理していないことは分かるので。

2020-05-19 09:50 UTC, shunji-yamaguchi commented on src/kadai13/kadai13_3/Wizard.java
> +    void heal(Hero h) {
`heal`メソッドがパッケージプライベートのままになっています。

2020-05-19 09:50 UTC, shunji-yamaguchi commented on src/kadai13/kadai13_4/Wizard.java
> +    void heal(Hero h) {
`heal`メソッドがパッケージプライベートのままになっています。

2020-05-20 08:10 UTC, RyuyaMaeda commented
@shunji-yamaguchi 
レビューありがとうございます。
以下の点で追加と修正をしました。
・変数名がわかりにくいため変数名hをheroに変更
・例外時の"処理を中断しました"という表現が不要なため削除
・同じパッケージのインスタンスしか回復できないのはおかしいのでpackage privateからpublicに修正
・powerフィールドとhealメソッドのドキュメンテーションコメントを記載した
よろしくお願いします。

2020-05-25 12:44 UTC, shunji-yamaguchi approved these changes
@RyuyaMaeda 良いと思います 🆗

2020-05-26 09:24 UTC, kimidoriam approved these changes
確認しました。良いと思います :ok_woman:

2020-05-27 00:05 UTC, merged