Kadai14
RyuyaMaeda/Java-Study pull request #21
Opened 2020-05-19 08:15 UTC by RyuyaMaeda

@shunji-yamaguchi @kimidoriam 
14章の練習問題です。
レビューの方よろしくお願いします。

2020-05-25 13:30 UTC, shunji-yamaguchi requested changes
@RyuyaMaeda レビューしました、ご確認をよろしくお願いします。

2020-05-25 13:30 UTC, shunji-yamaguchi commented on src/kadai14/Account.java
> +        return false;
```java
if (account.accountNumber.trim().equals(this.accountNumber.trim()) == true) {
```
こちらのコードだと`true == true` または `false == true` を行うことになるので冗長です。
```java
if (account.accountNumber.trim().equals(this.accountNumber.trim())) {
```
とするのが良いです。
（Java以外の言語だとifの条件式にboolean以外を渡せるものがあり、その場合はtrueのときのみ条件を満たすとするために、`if (hoge == true) ` と書くことがあります）

さらに、46行目〜48行目は
```java
return account.accountNumber.trim().equals(this.accountNumber.trim());
```
とすれば良いと思います。
46行目でfalseとなっても、50行目で結局falseが返るので

2020-05-26 02:24 UTC, RyuyaMaeda commented on src/kadai14/Account.java
> +        return false;
@shunji-yamaguchi 
レビューありがとうございます。
冗長なコードの解消のため、
if (account.accountNumber.trim().equals(this.accountNumber.trim()) == true)を
return account.accountNumber.trim().equals(this.accountNumber.trim())としました。
よろしくお願いします。

2020-05-26 09:27 UTC, kimidoriam approved these changes
確認しました。良いと思います :ok_woman:

2020-05-26 12:35 UTC, shunji-yamaguchi approved these changes
@RyuyaMaeda 良いと思います 🆗

2020-05-27 00:06 UTC, merged