Kadai15
RyuyaMaeda/Java-Study pull request #22
Opened 2020-05-22 01:35 UTC by RyuyaMaeda

@shunji-yamaguchi @kimidoriam 
15章の練習問題です。
レビューの方よろしくお願いします。

2020-05-26 10:00 UTC, kimidoriam requested changes
レビューしました。ご確認をお願いします。

2020-05-26 10:00 UTC, kimidoriam commented on src/kadai15/kadai15_4/Main.java
> +import java.time.format.*;
ワイルドカードインポートは使わないほうがよいです。

2020-05-27 00:28 UTC, RyuyaMaeda commented on src/kadai15/kadai15_4/Main.java
> +import java.time.format.*;
@kimidoriam 
レビューありがとうございます。
ワイルドカードを使用しないインポートに変更しました。
よろしくお願いします。

2020-05-27 12:09 UTC, shunji-yamaguchi approved these changes
@RyuyaMaeda 良いと思います 🆗

2020-06-05 08:24 UTC, kimidoriam approved these changes
確認しました。良いと思います :ok_woman:

2020-06-05 09:02 UTC, merged