Kadai16
RyuyaMaeda/Java-Study pull request #23
Opened 2020-05-25 02:10 UTC by RyuyaMaeda

@shunji-yamaguchi @kimidoriam 
16章の練習問題です。レビューの方よろしくお願いします。

2020-05-27 12:26 UTC, shunji-yamaguchi requested changes
@RyuyaMaeda レビューしました、ご確認よろしくお願いします。

2020-05-27 12:26 UTC, shunji-yamaguchi commented on src/kadai16/kadai16_3/Main.java
> +        Map<Hero, Integer> heroes = new HashMap<Hero, Integer>();
こちらも右辺の型指定は省略できます。

2020-05-27 12:26 UTC, shunji-yamaguchi commented on src/kadai16/kadai16_2/Main.java
> +        List<Hero> heroes = new ArrayList<Hero>();
右辺のダイヤモンド演算子`<>`での型指定は省略できます。
なので省略してしまえば良いです。

2020-05-28 00:29 UTC, RyuyaMaeda commented on src/kadai16/kadai16_3/Main.java
> +        Map<Hero, Integer> heroes = new HashMap<Hero, Integer>();
@shunji-yamaguchi 
レビューありがとうございます。
右辺のダイヤモンド演算子を省略しました。
よろしくお願いします。

2020-05-28 09:49 UTC, shunji-yamaguchi requested changes
@RyuyaMaeda レビューしました、ご確認よろしくお願いします。

2020-05-28 09:49 UTC, shunji-yamaguchi commented on src/kadai16/kadai16_2/Main.java
> +        List<Hero> heroes = new ArrayList();
型だけでなく`<>`も省略していますね。
これはJava5以前の、Listに格納できる要素の型指定ができなかったころの書き方です。
そのため使用しないのがよいです。
`<>`は省略せず`new ArrayList<>();`としましょう。

以下の記事が参考になりました。（`new ArrayList();`でも動くの知らなかった）
https://qiita.com/taumax/items/2af451a2c331e8ded892

2020-05-28 09:49 UTC, shunji-yamaguchi commented on src/kadai16/kadai16_3/Main.java
> +        Map<Hero, Integer> heroes = new HashMap();
こちらも`new HashMap<>();`としましょう

2020-05-29 01:27 UTC, RyuyaMaeda commented on src/kadai16/kadai16_2/Main.java
> +        List<Hero> heroes = new ArrayList();
@shunji-yamaguchi 
レビューとジェネリスクに関するリンクを貼っていただいてありがとうございました。
右辺は型指定だけを省略して<>を追加しました。
よろしくお願いします。

2020-05-29 04:20 UTC, shunji-yamaguchi approved these changes
@RyuyaMaeda 良いと思います 🆗

2020-06-05 08:27 UTC, kimidoriam approved these changes
レビューしました。良いと思います :ok_woman:

2020-06-05 09:02 UTC, merged