Kadai1
RyuyaMaeda/Java-Study pull request #8
Opened 2020-04-24 08:07 UTC by RyuyaMaeda

@shunji-yamaguchi  
@kimidoriam 
第一章の練習問題です。
レビューの方よろしくお願いします

2020-04-24 09:33 UTC, kimidoriam requested changes
@RyuyaMaeda 
レビューしました。ご確認お願いします。

2020-04-24 09:33 UTC, kimidoriam commented on src/kadai1/kadai1_2.java
> +//画面に”縦幅３横幅５の長方形の面積は、１５”と表示するソースコードの作成
1行コメントの場合は`//`のあとにスペースを入れると良いです。
また、1行コメントと複数行コメントが混在しているので、統一すると良いです。
クラスの説明なのでJavadocでも良いと思います。

2020-04-24 09:33 UTC, kimidoriam commented on src/kadai1/kadai1_2.java
> +
改行が余分に入っています。

2020-04-24 09:33 UTC, kimidoriam commented on src/kadai1/kadai1_3.java
> + */
複数行コメントは、以下のことを意識してみてください。
- アスタリスク`*`の位置を揃える
- 1行目にはコメントを書かない
```Java
/* 
 * 以下に示した～
 * true
 * ...
 */
```

2020-04-24 09:33 UTC, kimidoriam commented on src/kadai1/kadai1_2.java
> +
細かいですがこの改行は不要に思います。

2020-04-27 00:09 UTC, shunji-yamaguchi requested changes
@RyuyaMaeda 
レビューしました、ご確認をよろしくお願いします。

2020-04-27 00:09 UTC, shunji-yamaguchi commented on src/kadai1/kadai1_2.java
>  public class kadai1_2 {
`kadai1_2`はクラス名ですね。
Javaではクラス名はアッパーキャメルケースで記述するのが一般的です。
（先頭と単語の区切りを大文字で表現する 例：UpperCamelCase）
ファイル名も、ファイル内のクラス名と同じ名前をつけるべきなので、同様に修正をお願いします。

クラスについては後の章で説明があると思うので、今はわからなくても良いです。

2020-04-27 00:09 UTC, shunji-yamaguchi commented on src/kadai1/kadai1_3.java
> +public class kadai1_3 {
`kadai1_3`についてもアッパーキャメルケースへの修正をお願いします。

2020-04-27 02:21 UTC, RyuyaMaeda commented
@kimidoriam @shunji-yamaguchi 
レビューありがとうございます。課題１の以下の修正をしました。よろしくお願いします。
- クラス名をアッパーキャメルケースに変更
- コメントをJavaDoc形式に変更
- 不要な改行の削除

2020-04-27 02:40 UTC, RyuyaMaeda commented
@kimidoriam @shunji-yamaguchi 
レビューありがとうございます。課題１の以下の修正をしました。よろしくお願いします。
- クラス名をアッパーキャメルケースに変更
- コメントをJavaDoc形式に変更
- 不要な改行の削除

2020-04-27 08:21 UTC, kimidoriam commented on src/kadai1/kadai1_2.java
> +
こちらがまだ修正されていないようです。

2020-04-27 08:31 UTC, RyuyaMaeda commented on src/kadai1/kadai1_2.java
> +
@kimidoriam 
失礼しました。
修正しましたので再度レビューよろしくお願いします。

2020-04-27 08:33 UTC, kimidoriam requested changes

2020-04-27 08:33 UTC, kimidoriam commented on src/kadai1/Kadai1_2.java
> +}
![image](https://user-images.githubusercontent.com/38206336/80351253-fe466480-88ac-11ea-9efa-93e8456eaf64.png)
ファイル末尾に改行がないとGitHubからこのように怒られますので1行だけ空けましょう。

2020-04-27 08:47 UTC, RyuyaMaeda commented on src/kadai1/Kadai1_2.java
> +}
@kimidoriam 
失礼しました、末尾の修正をしました。
レビューよろしくお願いします。

2020-04-27 08:47 UTC, kimidoriam approved these changes
良いと思います :ok_woman:

2020-04-28 00:00 UTC, shunji-yamaguchi approved these changes
@RyuyaMaeda 
良いと思います 🆗

2020-04-28 01:52 UTC, merged