Kadai2
RyuyaMaeda/Java-Study pull request #9
Opened 2020-04-24 08:27 UTC by RyuyaMaeda

@shunji-yamaguchi
@kimidoriam
第二章の練習問題です。
レビューの方よろしくお願いします

2020-04-27 01:25 UTC, shunji-yamaguchi requested changes
@RyuyaMaeda 
レビューしました、ご確認をよろしくお願いします。

2020-04-27 01:25 UTC, shunji-yamaguchi commented on src/kadai2/kadai2_3.java
> +
不要な改行なので削除しておいてください。

2020-04-27 01:25 UTC, shunji-yamaguchi commented on src/kadai2/kadai2_3.java
> +public class kadai2_3 {
Kadai1のプルリクエストで指摘した通り、アッパーキャメルケースに修正するのが良いです。

2020-04-27 01:25 UTC, shunji-yamaguchi commented on src/kadai2/kadai2_1.java
> +public class kadai2_1 {
Kadai1のプルリクエストで指摘した通り、アッパーキャメルケースに修正するのが良いです。

2020-04-27 01:25 UTC, shunji-yamaguchi commented on src/kadai2/kadai2_1.java
> +        String ans = "x+yは" + (x + y);
問題文で提示されたプログラムで`ans`となっていますが、名前はわかりやすさが大切なので省略しないほうが良いです。
修正しても良いかなと思いました。

2020-04-27 01:25 UTC, shunji-yamaguchi commented on src/kadai1/kadai1_2.java
> +
Kadai1のプルリクエストで三浦さんが指摘されてましたが、コメントはJavaDoc形式で書いておくと良いと思います。
```java
/**
 * コメント
 * 2行目のコメント
 */
public class kadai1_2 {
```
IntelliJだと`kadai1_2`にカーソルを持ってきてContril+JするとJavaDocのコメントを表示してくれます。

2020-04-27 01:57 UTC, RyuyaMaeda commented
@kimidoriam @shunji-yamaguchi 
レビューありがとうございます。二章の以下の修正をしました。よろしくお願いします。
- クラス名をアッパーキャスト記法に変更
- 変数名をans -> answerに変更
- コメントをJavaDoc形式に変更
- 不要な改行の削除

2020-04-27 02:41 UTC, RyuyaMaeda commented
@kimidoriam @shunji-yamaguchi 
レビューありがとうございます。二章の以下の修正をしました。よろしくお願いします。
- クラス名をアッパーキャスト記法に変更
- 変数名をans -> answerに変更
- コメントをJavaDoc形式に変更
- 不要な改行の削除

2020-04-28 00:05 UTC, shunji-yamaguchi approved these changes
@RyuyaMaeda 
良いと思います 🆗

2020-04-28 02:45 UTC, kimidoriam approved these changes
良いと思います :ok_woman:

2020-04-28 04:16 UTC, merged